server:
  port: 8005

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

spring:
  application:
    name: invigilate
  servlet:
    multipart:
      #上传文件的最大值
      max-file-size: 15MB
      #请求文件的最大值
      max-request-size: 50MB


knife4j:
  enable: true
  basic:
    enable: true
    username: webdev403
    password: webdev403
  documents:
    - group: 1.0
      name: 相关说明文档
      locations: classpath:markdown/*


guardian:
  token:
    private-key: 'hfut-software-lab'
    header-name: 'token'
    prefix: ''
  interceptor:
    exclude-path-patterns: ["/error","/swagger-resources/**"]
