spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invigilate?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: phpmyadmin
    password: newx
#  boot:
#    admin:
#      client:
#        url: http://110.40.157.12:8004/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: ALWAYS